title: pyoomph
description: A finite element framework in Python, based on oomph-lib and GiNaC
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
